name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Debug: Check if SSH key is passed
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" | head -n 5
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/phonix-scripts/
            git pull origin main
            docker build -t phonix-scripts .
            docker stop phonix-scripts || true
            docker rm phonix-scripts || true
            docker run \
            --add-host=host.docker.internal:host-gateway \
            --env AWS_REGION=eu-west-3 \
            -p 3000:3000 \
            -d \
            --restart=always \
            --env-file .env \
            --name phonix-scripts \
            phonix-scripts
